CREATE TABLE `data_restaurant` (
  `ID` int NOT NULL,
  `name_english` varchar(200) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci DEFAULT NULL,
  `name_korean` varchar(200) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci DEFAULT NULL,
  `type_muslimfriendly` int DEFAULT NULL,
  `type_food1` int DEFAULT NULL,
  `type_food2` int DEFAULT NULL,
  `type_food3` int DEFAULT NULL,
  `address_english` varchar(200) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci DEFAULT NULL,
  `address_korean` varchar(200) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci DEFAULT NULL,
  `lat` double DEFAULT NULL,
  `lng` double DEFAULT NULL,
  `info_phonenumber` varchar(200) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci DEFAULT NULL,
  `info_seatnumber` int DEFAULT NULL,
  `info_parking` tinyint DEFAULT NULL,
  `info_wudu` tinyint DEFAULT NULL,
  `info_rug` tinyint DEFAULT NULL,
  `info_genderwashroom` tinyint DEFAULT NULL,
  `info_hookah` tinyint DEFAULT NULL,
  `info_alcoholfree` tinyint DEFAULT NULL,
  `info_muslimcooks` tinyint DEFAULT NULL,
  `info_halalingredient` tinyint DEFAULT NULL,
  PRIMARY KEY (`ID`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb3